mysql:
  url: jdbc:mysql://localhost:3306/app_installation_system?useSSL=false&serverTimezone=UTC
  user: root
  password: root@123

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl_auto: update

influxdb:
  url: http://localhost:8086
  token: F_JfcXA2SJq883W9Izpr4iyqlFOv_jNoGZQpTBtafCMb1J3992XgnZ6ejpKKb8-bF1AwDLzRW9jpuxprQUftoQ==
  org: miko
  bucket: app_installation_system

http:
  port: 8080
