mysql:
  url: jdbc:mysql://localhost:3306/app_installation_system?useSSL=false&serverTimezone=UTC
  user: root
  password: root@123

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl_auto: update

influxdb:
  url: http://localhost:8086
  username: admin
  password: admin
  database: logs_db

http:
  port: 8080
